"""composteira e compostagens tables

Revision ID: 14dce6b93e6e
Revises: 7a4120fad406
Create Date: 2025-08-18 11:26:00.679103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14dce6b93e6e'
down_revision: Union[str, None] = '7a4120fad406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('composteiras_table',
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('minhocas', sa.Boolean(), nullable=False),
    sa.Column('data_construcao', sa.String(), nullable=False),
    sa.Column('regiao', sa.String(), nullable=False),
    sa.Column('tamanho', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('fkUsuario', sa.String(), nullable=False),
    sa.Column('id_composteira', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['fkUsuario'], ['users_table.id'], ),
    sa.PrimaryKeyConstraint('id_composteira')
    )
    op.create_table('compostagens_table',
    sa.Column('data_inicio', sa.String(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('frequencia', sa.String(), nullable=False),
    sa.Column('fkComposteira', sa.String(), nullable=False),
    sa.Column('fkUsuario_comp', sa.String(), nullable=False),
    sa.Column('id_compostagem', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['fkComposteira'], ['composteiras_table.id_composteira'], ),
    sa.ForeignKeyConstraint(['fkUsuario_comp'], ['users_table.id'], ),
    sa.PrimaryKeyConstraint('id_compostagem')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('compostagens_table')
    op.drop_table('composteiras_table')
    # ### end Alembic commands ###
