"""Initial_Schema_Final

Revision ID: 27c80d0fe85c
Revises: 2cd54f950fd5
Create Date: 2025-11-19 10:44:45.334642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27c80d0fe85c'
down_revision: Union[str, None] = '2cd54f950fd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=True),
    sa.Column('last_name', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('date_joined', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('composteiras_table',
    sa.Column('fkUsuario', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('minhocas', sa.Boolean(), nullable=False),
    sa.Column('data_construcao', sa.Date(), nullable=False),
    sa.Column('regiao', sa.String(), nullable=False),
    sa.Column('tamanho', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id_composteira', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['fkUsuario'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('id_composteira')
    )
    op.create_table('compostagens_table',
    sa.Column('data_inicio', sa.String(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('frequencia', sa.String(), nullable=False),
    sa.Column('fkComposteira', sa.String(), nullable=False),
    sa.Column('fkUsuario_comp', sa.Integer(), nullable=False),
    sa.Column('id_compostagem', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['fkComposteira'], ['composteiras_table.id_composteira'], ),
    sa.ForeignKeyConstraint(['fkUsuario_comp'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('id_compostagem')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('compostagens_table')
    op.drop_table('composteiras_table')
    op.drop_table('auth_user')
    # ### end Alembic commands ###
