"""create all tables

Revision ID: 7a4120fad406
Revises: 
Create Date: 2025-07-01 10:27:45.408268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a4120fad406'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_table',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('composteiras_table',
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('minhocas', sa.Boolean(), nullable=False),
    sa.Column('data_constru', sa.String(), nullable=False),
    sa.Column('regiao', sa.String(), nullable=False),
    sa.Column('tamanho', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compostagens_table',
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('data_compostagem', sa.String(), nullable=False),
    sa.Column('quantReduo', sa.Float(), nullable=False),
    sa.Column('frequencia', sa.String(), nullable=False),
    sa.Column('previsao', sa.Integer(), nullable=False),
    sa.Column('composteira_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['composteira_id'], ['composteiras_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('compostagens_table')
    op.drop_table('composteiras_table')
    op.drop_table('users_table')
    # ### end Alembic commands ###
